service: helloworld
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  test:
    handler: handler.test
    events:
      - httpApi:
          path: /test
          method: get